### ISSUE TITLE
Incorrect deleted range after inserting a character

### ISSUE THREAD

**Issue by floorish** [ProseMirror/prosemirror-changeset#6]
To reproduce:
(using `[fromA, toA, fromB, toB]` notation, `|` denotes the cursor)

```
ab|c                                  []
<delete b>       + [2, 3, 2, 2]
a|c                                   = [2, 3, 2, 2]
<insert x>       + [2, 2, 2, 3]
ax|c                                  = [2, 3, 2, 3]
<move left>      + []
a|xc                                  = [2, 3, 2, 3]
<insert x>       + [2, 2, 2, 3]
ax|xc                                 = [2, 4, 2, 4] ?
```

The resulting change is `[2, 4, 2, 4]` instead of expected `[2, 3, 2, 4]`. In the last step the `change.toA` has been increased by one (3 -> 4), but it only has an insertion and no deletion.

I think I've narrowed the issue down to the `Change.merge` method, which incorrectly merges `[2, 3, 2, 3]`  with `[2, 2, 2, 3]`. Tests have been added here: https://github.com/floorish/prosemirror-changeset/commit/ac73ee1ebb0502dd7fc0cf6a4efbe471ba1f7f0a and here (`Change.merge` tests): https://github.com/floorish/prosemirror-changeset/commit/213024b04f4dc059fd65513e58f4cd51930162f3

I'm not sure how to fix this, since the `Change.merge` method is pretty complex. The inner loop is iterated twice and in each iteration `toA` (incorrect) and `toB` (correct) are both increased by one.

Any clues how to fix this?

**Comment by floorish** [comment]
@marijnh Any pointers on how to fix this? We are running into this bug quite a lot, but we can't figure out exactly how the `merge` function is supposed to work. Is it based on an existing algorithm?

In the above described test case the following snippet is executed twice:
```
if (inX && pos == curX.fromB) {
   deleted = Span.join(deleted, curX.deleted, combine)
   toA += curX.lenA
}
```
Which means that the `deleted` part from the same `curX` is added twice.
To prevent that I can replace that snippet with:
```
if (inX && pos == curX.fromB && (next != curX.fromB || next == curX.toB)) {
   deleted = Span.join(deleted, curX.deleted, combine)
  toA += curX.lenA
}
```
I think this is a pretty reasonable fix, however `ChangeSet fuzz issue 2` fails due to this change:
`[[3,10,3,10,[[2,0],[5,2]],[[7,0]]]] != [[3,12,3,10,[[2,0],[5,2],[2,0]],[[7,0]]]]`

Looking at that fuzz test, I think the expected value is incorrect. The expected deleted range as written in the tests is `3, 12`, but the initial input does not even have that length! (`eAMISWgauf`) So the result with proposed fix sounds more logical `3,10,3,10` instead of `3,12,3,10`. Could it be that the fuzz test is therefore incorrect?

**Comment by marijnh** [comment]
Oh, right, sorry about the slow response. This is some extremely tricky code and I've been having too much other stuff going on to make time to look into it.

>  Is it based on an existing algorithm?

No, it's something I made up, and it's not surprising that it still has problems. Basically, it takes a set of changes that go from document A to document B, and a set of changes from B to C, and produces a set of changes from A to C. In doing so, it makes sure it merges changes that touch (in document B), so that the result set still has the invariant that groups of changes are separated by some unchanged space.

The big loop loops over both arrays, and at each iteration, it checks for the case

 - where both are done
 - where `curX` is in front of `curY`, and thus has to have its `b` side mapped to span to document C and added to `result`
 - where `curY` is in front of `curX`, and thus has to have its `a` side mapped to point at document A and added to `result`
 - the changes touch/overlap, so they have to be merged, which involves a bunch more code

That inner loop in the last branch moves over a position in document B (`pos`), doing one iteration per 'range', treating each start and end point of the group of touching ranges as a boundary (so that on each iteration, the range it handles either has only one change active, or two changes active.

Your bug report sounds like it has a bug, and indeed, handling the same `curX` twice with `inX == true` should not happen.

I'm not going to have time to debug and fix this in the near future, though, so if you want to dig deeper into this that'd be welcome.

**Comment by floorish** [comment]
Thanks for the response. I've created a pull request with the above mentioned changes. It's more like a *patch* (prevents handling the same `curX` twice) than a structural fix (prevent considering `curX` twice at all), but it does work.

Do you agree that the expected value of `ChangeSet fuzz issue 2` was incorrect? I have changed the expected value of that test as well in the pull request.

Related to the explanation of the algorithm, this particular part looks strange:
```
} else if (curY && (!curX || curY.toA < curY.fromB)) { // curY entirely in front of curX
```
How can you conclude that `curY` is in front of `curX` when only `toA` and `fromB` from `curY` are checked? Looks like it works fine, but just wondering how that works.

**Comment by marijnh** [comment]
> Related to the explanation of the algorithm, this particular part looks strange:

It does, and it looks like that should say `curX.fromB` at the end. Shall I update that or do you want to create a patch yourself?

**Comment by marijnh** [comment]
(See my comment on the PR for the rest of my feedback.)

**Comment by floorish** [comment]
> It does, and it looks like that should say curX.fromB at the end. Shall I update that or do you want to create a patch yourself?

Yes that's what I thought as well. That part isn't covered by any tests though, so I'm a bit hesitant to fix something which isn't broke (yet). 

Changing it to `curX.fromB` only changes this test (from my branch):
```
Change.merge([[1, 1, 1, 3]] , [[0, 0, 0, 2], [2, 2, 6, 8]] )
-> output [[0,0,0,2],[1,1,3,7]]
```
It seems like that is indeed the expected output. (Previously the output was `[[0,0,0,2],[2,2,6,8],[1,1,7,9]]`, which is definitely incorrect)

I'll make a pull request for that.

**Comment by marijnh** [comment]
Thanks. Apologies about the code quality of this module—I found myself rewriting the whole thing after version 1 it to address some design mistakes that I started with, but at a time where I really wanted to be doing something else, so it's all a bit rushed.
